<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
class ClientData extends Model
{
    protected $table = 'client'; // Specify the table name

    protected $primaryKey = 'ClientID'; // Set the primary key

    public $incrementing = false; // Indicate that the primary key is non-incrementing

    protected $keyType = 'string'; // Set the key type as string

    protected $fillable = [
        'ClientID',
        'ExpectedFinishTimeofAppointment',
        'AlternativeDates',
        'EndUserilliterate',
        'startTimeofAppointment',
        'endUserMobile',
        'endUserEmail',
        'targetLanguage',
        'yourEmailID',
        'yourContactNumber',
        'BudgetHolderName',
        'contactPersonEmail',
        'BudgetHolderContact',
        'BudgetHolderEmail',
        'ClientJobReferenceNumber',
        'DeptOrTypeofCase',
        'CostCentreCode',
        'IsClientInclusive',
        'DontChargeTravelTime',
        'TrustServices',
        'OtherTrusts',
        'OtherNature',
        'TrustLocationAddress',
        'IsInclusiveForInterpreters',
        'SendSMSToEndUser',
        'SendEmailReminderToEndUser',
        'ShowTimeSheetOnline',
        'PayTravelTimeToInterpreterAfter',
        'AfterHowManyMilesToChargeMileage',
        'ChargeTravelTimeToClientAfter',
        'AfterHowManyMilesToPayMileageToLinguist',
        'SubOffice',
        'DoyouhaveaLocationSessionID',
        'DoYouHaveApproval4ThisBooking',
        'ReasonF2FInterprterNeeded',
        'AnyHealthSafetyHazzards',
        'GenderofInterpreter',
        'Officer',
        'ClientCaller',
        'DNA',
        'InterpreterPaid',
        'PayInterpreter',
        'BookingAddressPostCode',
        'BookingAddress3',
        'BookingAddress2',
        'BookingAdress1',
        'HouseNo',
        'BookingAddressID',
        'telephoneinterpreting',
        'remotevideointerpreting',
        'remotebslvideointerpreting',
        'skypeforbusiness',
        'whatsapp',
        'teams',
        'zoom',
        'f2finterpreting',
        'transcription',
        'translation',
        'ServiceType',
        'ClientClientName',
        'show_review_inclient_admin',
        'show_review_inclient',
        'ccAdminEmail',
        'clientAdminEmail',
        'adminNeedEmailConfirmation',
        'client_admin_password',
        'reject_booking',
        'approved_booking',
        'haveclientadmin',
        'isold',
        'savings_chart_for_client',
        'cancellation_chart_for_client',
        'response_chart_for_client',
        'savings_chart_for_client_admin',
        'cancellation_chart_for_client_admin',
        'response_chart_for_client_admin',
        'RVIRate',
        'BSLVideoRate',
        'ChargeClientByMinuteAfter1stHr',
        'ChargeClientNormalRate4OutOfhours',
        'ChargeClientFixedHrlyRate4OutOfHrs',
        'OutOfOfficeHoursStartsAt',
        'OutOfOfficeHoursEndsAt',
        'RatePerMile2Client',
        'reject_booking_client_user',
        'appointment',
        'appointment_type',
        'attendees',
        'is_aleady_worked',
        'papers_being_referred',
        'TelPoneRate',
        'ClientTelephoneRatePerMin',
        'ClientVideoRatePerMin',
        'ClientAgencyRating',
        'ClientSpecialRateAmountTelephonePerMin',
        'ClientSpecialRateAmountVideo',
        'Client3rdPartyTelephoneConferenceFeePerMinute',
        'Client3rdPartyVideoConferenceFeePerMinute',
        'ClientMinimumFeeAudio',
        'ClientMinimumFeeVideo',
        'ClientMinimumDurationAudio',
        'ClientMinimumDurationVideo',
        'IsProvidePatientLink'
    ];
}
