  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="vinod/css/froala_editor.css">
  <link rel="stylesheet" href="vinod/css/froala_style.css">
  <link rel="stylesheet" href="vinod/css/plugins/code_view.css">
  <link rel="stylesheet" href="vinod/css/plugins/image_manager.css">
  <link rel="stylesheet" href="vinod/css/plugins/image.css">
  <link rel="stylesheet" href="vinod/css/plugins/table.css">
  <link rel="stylesheet" href="vinod/css/plugins/video.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/codemirror.min.css">
